baseurl = "https://sambhavjain.netlify.com/blog"
title = "sambhav2612"
theme = "vec"
languageCode = "en-us"
paginate = 15
disqusShortname = "sambhav2612"
googleAnalytics = "UA-107733371-4"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "posts"
    weight = 0
    url = "/post"
  [[menu.main]]
    name = "contact"
    weight = 1
    url = "/contact"
  [[menu.main]]
    name = "faq"
    weight = 2
    url = "/faq"

[params]
  Keywords = ""
  Description = "There are some words to describe your site"
  Avatar = "img/avatar.jpg"
  SelfIntro = "Just a worm, seeking for truth, living in shadows, not anymore..."
  Email = "sambhavjain2612gmail.com"

  GithubID = "sambhav2612"
  TwitterID = "sambhavvjain"
  FacebookID = "sambhav2612"
  LinkedInID = "sambhav2612"
